name: Patch Video Download Helper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Extension CRX
        run: |
          curl -L "https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&prod=edgecrx&os=win&arch=x64&osArch=x64&nacl_arch=x86-64&prodchannel=unknown&prodversion=120.0.0.0&acceptformat=crx3&x=id%3Djmkaglaafmhbcpleggkmaliipiilhldn%26installsource%3Dondemand%26uc" -o vdh_original.crx

      - name: Extract CRX
        run: |
          mkdir vdh_ext
          7z x vdh_original.crx -ovdh_ext
          
          rm -rf vdh_ext/_metadata

      - name: Check if Release exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          EXT_VERSION=$(jq -r '.version' vdh_ext/manifest.json)
          
          if gh release view "v$EXT_VERSION" -R ${{ github.repository }} &>/dev/null; then
            echo "Release v$EXT_VERSION đã tồn tại. Bỏ qua các bước tiếp theo."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Bản mới v$EXT_VERSION. Tiếp tục patch và release."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Patch service/main.js and inject key
        if: steps.check.outputs.skip != 'true'
        run: |
          sed -i 's/qn=!1/qn=!0/g' vdh_ext/service/main.js
          
          if grep -q "qn=!0" vdh_ext/service/main.js; then
            echo "Patch successful!"
          else
            echo "Patch failed! String not found."
            exit 1
          fi

          jq '.key = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAphdbW9Bk/84LQ9NEfbv5yO/mvJmDidcumtRCs+RZmMHU/6XIzFtEpoCrrNq2alPLkLawQPFiL/Efc67Hf8Kzi+U1pEr4re+dOT47v51Wf58VEz17KK4DPD2D/sctxjVZpMzusbntbSfPy61gMVEQpQw4Ta/5+/8xTFPfWJHd+H987qRAAMrMW/jz3V/92/ZHbnBxEI/aYkB6g1m0rn43OERKlcvVn3v42qKiEOOnHsrlfqvuKm5cMIwcb0kp7r1dryoMX3T2PtsFO8VtItudjG/67rhDk0Hm0+gZC3CbkknHQwmGcQCVrzHVpBbUh1n8au7KDCKoJFSBNKGiLmFcTQIDAQAB"' vdh_ext/manifest.json > vdh_ext/manifest_tmp.json
          mv vdh_ext/manifest_tmp.json vdh_ext/manifest.json

      - name: Repack to ZIP
        if: steps.check.outputs.skip != 'true'
        run: |
          EXT_VERSION=$(jq -r '.version' vdh_ext/manifest.json)
          echo "VERSION=$EXT_VERSION" >> $GITHUB_ENV

          cd vdh_ext
          zip -r ../video-download-helper_${EXT_VERSION}.zip *
          
          cp ../video-download-helper_${EXT_VERSION}.zip ../video-download-helper_latest.zip

      - name: Upload Patched ZIP Artifact
        if: steps.check.outputs.skip != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: VDH-Patched-ZIP
          path: video-download-helper_${{ env.VERSION }}.zip
          retention-days: 7

      - name: Create Release
        if: steps.check.outputs.skip != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Video Download Helper v${{ env.VERSION }}
          files: |
            video-download-helper_${{ env.VERSION }}.zip
            video-download-helper_latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
